my:
   greeting: Hello
   list:
       values: one,two,three

dbValues: "{connectionString: 'http://___',userName: 'foo',password: 'pass'}"


db:
   connection: "{connectionString: 'http://___',userName: 'foo',password: 'pass'}"
   host: 127.0.01
   port: 1200

management.endpoints.web.exposure.include: "*"








#app.name: My app
#app.description: Welcome tp ${my.greeting}
spring:
   profiles:
      active: test
